title: Gabriel Chen
email: gabrielchen@duck.com
description: > # this means to ignore newlines until "baseurl:"
    Shut Down The Heart, And Open Your Eyes.
permalink: ':title/'
baseurl: "" 
url: "" 

# Author settings
author: Gabriel Chen 
author-pic:
about-author: A hacker, who designs and redesigns computers and human beings.

# Contact links
email: gabrielchen@duck.com # Add your Email address
phone: # Add your Phone number
website: gabrielchen.com # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Paginate
paginate: 6
paginate_path: /page:num/

# collections
collections:
  - books
  - booktags
  - movies
  - movietags
  - images

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-feed

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
