title: Gabriel Chen
email: gabrielchen@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    Shut Down The Heart, And Open Your Eyes.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Gabriel Chen # add your name
author-pic:
about-author: I am an undergrad at UC Berkeley majors in Computer Science, and my study focuses on CS Theory. My research interests lie primarily in Computational Complexity, Algorithms Design, and Hardness of Computation. I also love surfing, archery, and abstract painting.

# Contact links
email: gabrielchen@berkeley.edu # Add your Email address
protonmail: gabriel.j.chen@protonmail.com
phone: # Add your Phone number
website: gabriel-chen.github.io # Add your website, do not add http://
linkedin: #gabrielchen0 # Add your Linkedin handle
github: gabriel-chen # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: UA-75034651-3 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-feed

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
